### ISSUE TITLE
What is the correct way to intialize patterns in Plone?

### ISSUE THREAD

**Issue by datakurre** [datakurre/plonetheme.webpack#3]
My experimental approach here is to completely bypass Plone resource registries, build bundles with webpack and include them with Diazo. Yet, something should initialize patterns after everything is loaded. What would be a proper way for that?

Currently, I simply call

```
   require('pat-registry').init();
```

in the main bundle, but that may have racing conditions and probably can only be executed once (and not at the end of every bundle) or can it?

/cc @thet @jcbrand @vangheem

**Comment by vangheem** [comment]
I think that call is unnecessary.

initialization is already called in the plone bundle and all subsequent pattern registrations added after the initialization should be immediately scanned for.

No race conditions or anything. I think your call will be silently ignored since it might have already been run and it already handles this.

**Comment by datakurre** [comment]
@vangheem Thanks. It seems that I had added manual init back when I only had toolbar patter building. Now everything works as you described.
